version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule: {interval: weekly}
  - package-ecosystem: github-actions
    directories: ["/", "/.github/actions/release-tools"]
    schedule: {interval: weekly}
  - package-ecosystem: docker
    directory: /
    schedule: {interval: weekly}
