version: 2
project_name: sievelog

before:
  hooks:
    - go mod verify

builds:
  - id: sievelog
    main: ./cmd/sievelog
    binary: sievelog
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files: [LICENSE, NOTICE, README.md]

checksum:
  name_template: checksums.txt
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  disable: true

release:
  github:
    owner: Bisman-Singh
    name: sievelog
  draft: true
