# The published image: the release binary goreleaser built for this platform, on distroless.
FROM gcr.io/distroless/static-debian12:nonroot@sha256:afa5c872c891853ca7fcf1f12c3edb23f7eeef36189728842dd51042ff57f7ab
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/sievelog /usr/local/bin/sievelog
COPY LICENSE NOTICE THIRD_PARTY_LICENSES /usr/share/doc/sievelog/
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/sievelog"]
